language: ruby
rvm:
  - 2.1.8
  - 2.2.2
  - 2.4.0
before_install: gem install bundler -v 1.13.7
addons:
    code_climate:
        repo_token: ebdc539bad445dc9ca96c4b01e2aa414624456bc47b3bf8b77c726c49b3158ba
